version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade awscli aws-sam-cli
      - sam --version

  pre_build:
    commands:
      - echo "Running tests (optional)"
      -
  build:
    commands:
      - echo "Building Lambda package"
      - sam build
      - echo "Packaging Lambda"
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
  discard-paths: yes
