version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade awscli aws-sam-cli

  build:
    commands:
      # - echo "Running tests..."
      - echo "Building artifact..."
      - sam build
      - sam package --s3-bucket $S3_BUCKET --output-template-file output-template.yml

artifacts:
  files:
    - output-template.yml