name: Deploy CloudFormation

on:
  push:
    branches:
      - main

env:
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  SNS_TOPIC: ${{ secrets.SNS_TOPIC }}
  SQS_QUEUE: ${{ secrets.SQS_QUEUE }}
  LAMBDA_NAME: ${{ secrets.LAMBDA_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  STACK_NAME: ${{ secrets.STACK_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION

      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy --template-file template.yaml --stack-name $STACK_NAME \
            --parameter-overrides \
              S3BucketName=$S3_BUCKET \
              SNSTopicName=$SNS_TOPIC \
              SQSQueueName=$SQS_QUEUE \
              LambdaFunctionName=$LAMBDA_NAME \
            --capabilities CAPABILITY_IAM
