name: Deploy CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy --template-file template.yaml --stack-name ${{ secrets.STACK_NAME }} \
            --parameter-overrides \
              S3BucketName=${{ secrets.S3_BUCKET }} \
              SNSTopicName=${{ secrets.SNS_TOPIC }} \
              SQSQueueName=${{ secrets.SQS_QUEUE }} \
              LambdaFunctionName=${{ secrets.LAMBDA_NAME }} \
            --capabilities CAPABILITY_IAM
